#!/bin/bash
set -euo pipefail
rm -rf /root/workshop/exercise /root/workshop/solution
cp -r /root/workshop/exercises/03_parallel_activities/practice /root/workshop/exercise
cp -r /root/workshop/exercises/03_parallel_activities/solution /root/workshop/solution
echo "Exercise 3 ready."
