#!/bin/bash
set -euo pipefail
rm -rf /root/workshop/exercise /root/workshop/solution
cp -r /root/workshop/exercises/05_saga/practice /root/workshop/exercise
cp -r /root/workshop/exercises/05_saga/solution /root/workshop/solution
echo "Exercise 5 ready."
