#!/bin/bash
set -euo pipefail
rm -rf /root/workshop/exercise /root/workshop/solution
cp -r /root/workshop/exercises/02_child_workflows/practice /root/workshop/exercise
cp -r /root/workshop/exercises/02_child_workflows/solution /root/workshop/solution
echo "Exercise 2 ready."
