#!/bin/bash
set -euo pipefail
rm -rf /root/workshop/exercise /root/workshop/solution
cp -r /root/workshop/exercises/01_converting/practice /root/workshop/exercise
cp -r /root/workshop/exercises/01_converting/solution /root/workshop/solution
echo "Exercise 1 ready."
